#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Apr 16 10:13:02 2021

@author: jorge
"""


import numpy as np
import matplotlib.pyplot as pl
import pandas as pd

data = ['default',
  'linked',
  'empathize_term',
  'empathize_category',
  'partial',
  'spellcheck',
  'default',
  'empathize_term',
  'back_from_pdp',
  'linked',
  'empathize_category',
  'empathize_trending',
  'back_from_search',
  'history',
  'next_query',
  'related_tag',
  'partial',
  'next_query_grid',
  'spellcheck',
  'default',
  'empathize_term',
  'back_from_pdp',
  'back_from_search',
  'linked',
  'partial',
  'history',
  'empathize_trending',
  'related_tag',
  'next_query',
  'spellcheck',
  'next_query_grid',
  'empathize_category',
  'default',
  'linked',
  'empathize_term',
  'related_tag',
  'history',
  'back_from_pdp',
  'back_from_search',
  'empathize_category',
  'empathize_trending',
  'partial',
  'next_query',
  'next_query_grid',
  'empathize_next_queries',
  'spellcheck',
  'next_query_grid',
  'default',
  'linked',
  'empathize_term',
  'related_tag',
  'empathize_category',
  'partial',
  'history',
  'next_query',
  'default',
  'efabhyg',
  'default',
  'empathize_category',
  'back_from_pdp',
  'linked',
  'empathize_term',
  'empathize_trending',
  'back_from_search',
  'next_query',
  'related_tag',
  'history',
  'partial',
  'next_query_grid',
  'empathize_next_queries',
  'spellcheck',
  'default',
  'empathize_term',
  'back_from_pdp',
  'back_from_search',
  'linked',
  'empathize_trending',
  'history',
  'next_query_grid',
  'partial',
  'related_tag',
  'empathize_next_queries',
  'spellcheck',
  'default',
  'linked',
  'empathize_category',
  'empathize_term',
  'partial',
  'spellcheck',
  'history'
]

pd.Series(data).value_counts().plot(kind='bar')